typeset -U PATH

# Prefer GB English and use UTF-8.
export LANG='en_GB.UTF-8';
export LC_ALL='en_GB.UTF-8';

export EDITOR=vim
export TIME_STYLE="long-iso"
export GITHUB_USER="mattoddie"

# Setup Go development
export TZ=UTC
export GOPATH=$HOME/go
export GO15VENDOREXPERIMENT=1

# Always enable colored `grep` output.
export GREP_OPTIONS='--color=auto';

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="robbyrussell"
export DISABLE_AUTO_UPDATE="true"
export COMPLETION_WAITING_DOTS="true"

# Say how long a command took, if it took more than 30 seconds
export REPORTTIME=30

# Skip the rest of this for non-interactive shells
[ -z "$PS1" ] && return

plugins=(aws heroku brew vagrant bundler screen sublime golang urltools node npm thefuck)

[[ -s "$ZSH/oh-my-zsh.sh" ]] && source $ZSH/oh-my-zsh.sh
unsetopt correct

[[ -s "$HOME/local.zsh" ]] && source $HOME/local.zsh

# Make it obvious we are running in screen
if [[ "$TERM" == "screen" ]]; then
	export PS1="%{$bg[white]%}%{$fg_bold[blue]%} SCREEN $reset_color%} $PS1"
fi

# Force local path first
export PATH=$GOPATH/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

alias reload!='. ~/.zshrc'
alias ll='ls -la'
alias rgrep='grep -R'
alias mkdir='mkdir -p'

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
