#!/usr/bin/env bash
set -e
# Download and install dotfiles

[ -d $HOME/.dotfiles ] && echo "Already installed" && exit 1

git clone https://github.com/bobbydeveaux/dotfiles.git ${HOME}/.dotfiles

${HOME}/.dotfiles/scripts/bootstrap